# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zms_card.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtPrintSupport import QPrinter,QPrintDialog,QPrintPreviewDialog
from PyQt5.QtWidgets import QApplication,QFileDialog,QMainWindow,QWidget
from PyQt5.QtGui import QIcon,QPixmap
from PyQt5.QtCore import *
import sys
import datetime
from PIL import ImageQt
import mss,os
import mss.tools
from PIL import Image


class Ui_MainWindow(object):
        def setupUi(self, MainWindow):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(608, 640)
                self.centralwidget = QtWidgets.QWidget(MainWindow)
                self.centralwidget.setObjectName("centralwidget")
                self.listWidget = QtWidgets.QListWidget(self.centralwidget)
                self.listWidget.setGeometry(QtCore.QRect(100, 40, 471, 281))
                self.listWidget.setStyleSheet("border:1px;\n"
                "border-radius:2px;")
                self.listWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.listWidget.setFrameShadow(QtWidgets.QFrame.Raised)
                self.listWidget.setMidLineWidth(1)
                self.listWidget.setObjectName("listWidget")
                self.label_4 = QtWidgets.QLabel(self.centralwidget)
                self.label_4.setGeometry(QtCore.QRect(230, 50, 301, 51))
                self.label_4.setMaximumSize(QtCore.QSize(302, 16777215))
                font = QtGui.QFont()
                font.setFamily("Ubuntu")
                font.setPointSize(12)
                font.setBold(True)
                font.setItalic(False)
                font.setWeight(75)
                self.label_4.setFont(font)
                self.label_4.setStyleSheet("color: rgb(4, 34, 200);\n"
                "font: 25 bold 12pt \"Ubuntu\";")
                self.label_4.setScaledContents(False)
                self.label_4.setObjectName("label_4")
                self.label = QtWidgets.QLabel(self.centralwidget)
                self.label.setGeometry(QtCore.QRect(80, 40, 151, 111))
                self.label.setText("")
                self.label.setPixmap(QtGui.QPixmap(self.resource_path("zms_badge.png")))
                self.label.setScaledContents(True)
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(self.centralwidget)
                self.label_2.setGeometry(QtCore.QRect(320, 130, 151, 16))
                font = QtGui.QFont()
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                self.label_2.setFont(font)
                self.label_2.setStyleSheet("color:rgb(255, 0, 0);")
                self.label_2.setObjectName("label_2")
                self.line = QtWidgets.QFrame(self.centralwidget)
                self.line.setGeometry(QtCore.QRect(220, 140, 91, 5))
                self.line.setBaseSize(QtCore.QSize(1, 0))
                font = QtGui.QFont()
                font.setPointSize(5)
                self.line.setFont(font)
                self.line.setStyleSheet("border:1px solid red;\n"
                "background-color:red;")
                self.line.setFrameShape(QtWidgets.QFrame.HLine)
                self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
                self.line.setObjectName("line")
                self.line_2 = QtWidgets.QFrame(self.centralwidget)
                self.line_2.setGeometry(QtCore.QRect(480, 140, 91, 5))
                self.line_2.setBaseSize(QtCore.QSize(1, 0))
                font = QtGui.QFont()
                font.setPointSize(5)
                self.line_2.setFont(font)
                self.line_2.setStyleSheet("border:1px solid red;\n"
                "background-color:red;")
                self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
                self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
                self.line_2.setObjectName("line_2")
                self.label_3 = QtWidgets.QLabel(self.centralwidget)
                self.label_3.setGeometry(QtCore.QRect(310, 100, 151, 16))
                font = QtGui.QFont()
                font.setPointSize(14)
                font.setBold(True)
                font.setItalic(False)
                font.setWeight(75)
                self.label_3.setFont(font)
                self.label_3.setStyleSheet("color:rgb(30, 158, 255);")
                self.label_3.setObjectName("label_3")
                self.label_5 = QtWidgets.QLabel(self.centralwidget)
                self.label_5.setGeometry(QtCore.QRect(110, 160, 121, 123))
                self.label_5.setStyleSheet("border:3px solid blue;\n"
                " border-radius:6px;")
                self.label_5.setText("")
                self.label_5.setPixmap(QtGui.QPixmap(self.resource_path("profile_pic.png")))
                #on click on pic
                self.label_5.mousePressEvent=self.load_pic
                
                self.label_5.setScaledContents(True)
                self.label_5.setObjectName("label_5")
                self.label_6 = QtWidgets.QLabel(self.centralwidget)
                self.label_6.setGeometry(QtCore.QRect(260, 170, 41, 21))
                self.label_6.setObjectName("label_6")
                self.student_name = QtWidgets.QLineEdit(self.centralwidget)
                self.student_name.setGeometry(QtCore.QRect(310, 170, 191, 28))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.student_name.setFont(font)
                self.student_name.setStyleSheet("color:rgb(0, 170, 0);\n"
                " border:none;\n"
                "background-color:none;")
                
                
                
                self.student_name.setInputMethodHints(QtCore.Qt.ImhUppercaseOnly)
                self.student_name.setObjectName("student_name")
                self.label_7 = QtWidgets.QLabel(self.centralwidget)
                self.label_7.setGeometry(QtCore.QRect(260, 220, 41, 21))
                self.label_7.setObjectName("label_7")
                self.c_class = QtWidgets.QLineEdit(self.centralwidget)
                self.c_class.setGeometry(QtCore.QRect(310, 220, 81, 21))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.c_class.setFont(font)
                self.c_class.setStyleSheet("color:rgb(0, 170, 0);\n"
                " border:none;")
                self.c_class.setInputMethodHints(QtCore.Qt.ImhNoTextHandles|QtCore.Qt.ImhUppercaseOnly)
                self.c_class.setObjectName("c_class")
                self.label_8 = QtWidgets.QLabel(self.centralwidget)
                self.label_8.setGeometry(QtCore.QRect(410, 220, 41, 21))
                self.label_8.setObjectName("label_8")
                self.c_year = QtWidgets.QLineEdit(self.centralwidget)
                self.c_year.setGeometry(QtCore.QRect(460, 220, 81, 28))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.c_year.setFont(font)
                self.c_year.setStyleSheet("color:rgb(0, 170, 0);\n"
                " border:none;")
                self.c_year.setInputMethodHints(QtCore.Qt.ImhDate)
                self.c_year.setObjectName("c_year")
                #adding year to c_year
                self.c_year.setText(self.current_year())
                #Integer validator
                self.onlyInt = QtGui.QIntValidator()
                #Text validator
                
                self.c_year.setValidator(self.onlyInt)
                self.label_9 = QtWidgets.QLabel(self.centralwidget)
                self.label_9.setGeometry(QtCore.QRect(260, 260, 81, 16))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_9.setFont(font)
                self.label_9.setObjectName("label_9")
                
                self.label_10 = QtWidgets.QLabel(self.centralwidget)
                self.label_10.setGeometry(QtCore.QRect(400, 260, 91, 16))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_10.setFont(font)
                self.label_10.setObjectName("label_10")
                self.label_11 = QtWidgets.QLabel(self.centralwidget)
                self.label_11.setGeometry(QtCore.QRect(110, 290, 41, 21))
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.label_11.setFont(font)
                self.label_11.setStyleSheet("color:blue;")
                self.label_11.setObjectName("label_11")
                
                self.i_exp_date = QtWidgets.QLineEdit(self.centralwidget)
                self.i_exp_date.setGeometry(QtCore.QRect(250, 290, 320, 20))
                font = QtGui.QFont()
                font.setPointSize(9)
                font.setBold(True)
                self.i_exp_date.setFont(font)
                self.i_exp_date.setStyleSheet("background-color:blue;\n"
                " color:white;\n"
                "border:1px;\n"
                " border-radius:10px;\n"
                " padding-left:5px;\n"
                " text-align:center;")
                self.i_exp_date.setObjectName("i_exp_date")
                #date of issue
                self.i_exp_date.setText(self.change_exp())
                
                
                
                self.id_num = QtWidgets.QLineEdit(self.centralwidget)
                self.id_num.setGeometry(QtCore.QRect(150, 290, 101, 28))
                #allow only integers
                self.id_num.setValidator(self.onlyInt)
                
                font = QtGui.QFont()
                font.setBold(True)
                font.setWeight(75)
                self.id_num.setFont(font)
                self.id_num.setStyleSheet("color:red;\n"
                " border:none;")
                self.id_num.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
                self.id_num.setObjectName("id_num")
                self.label_13 = QtWidgets.QLabel(self.centralwidget)
                self.label_13.setGeometry(QtCore.QRect(320, 150, 211, 141))
                self.label_13.setStyleSheet("opacity:200;")
                self.label_13.setText("")
                self.label_13.setPixmap(QtGui.QPixmap(self.resource_path("zms_badge.png")))
                self.label_13.setScaledContents(True)
                self.label_13.setObjectName("label_13")
                self.pushButton = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton.setGeometry(QtCore.QRect(100, 340, 90, 28))
                self.pushButton.setObjectName("pushButton")
                #printing id
                #self.pushButton.clicked.connect(lambda:self.handlePreview())
                self.pushButton.clicked.connect(lambda:self.compositeEvent())
                '''
                self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton_2.setGeometry(QtCore.QRect(460, 340, 90, 28))
                self.pushButton_2.setObjectName("pushButton_2")
                self.pushButton_2.clicked.connect(lambda:self.handlePreview())
                '''
                self.label_14 = QtWidgets.QLabel(self.centralwidget)
                self.label_14.setGeometry(QtCore.QRect(490, 150, 81, 61))
                self.label_14.setStyleSheet("opacity:127;")
                self.label_14.setText("")
                self.label_14.setPixmap(QtGui.QPixmap(self.resource_path("zms_badge.png")))
                self.label_14.setScaledContents(True)
                self.label_14.setObjectName("label_14")
                self.label_13.raise_()
                self.listWidget.raise_()
                self.label_4.raise_()
                self.label.raise_()
                self.label_2.raise_()
                self.line.raise_()
                self.line_2.raise_()
                self.label_3.raise_()
                self.label_5.raise_()
                self.label_6.raise_()
                self.label_7.raise_()
                self.c_class.raise_()
                self.label_8.raise_()
                self.c_year.raise_()
                self.label_9.raise_()
                self.label_10.raise_()
                self.label_11.raise_()
                self.i_exp_date.raise_()
                self.id_num.raise_()
                self.pushButton.raise_()
                #self.pushButton_2.raise_()
                self.label_14.raise_()
                self.student_name.raise_()
                MainWindow.setCentralWidget(self.centralwidget)
                self.statusbar = QtWidgets.QStatusBar(MainWindow)
                self.statusbar.setObjectName("statusbar")
                MainWindow.setStatusBar(self.statusbar)
                

                self.retranslateUi(MainWindow)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)
                
                

        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "ZANA MIXED S.S ID TEMPLATE"))
                self.label_4.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; font-style:normal;\"><br/></span></p></body></html>"))
                self.label_4.setText(_translate("MainWindow", "      ZANA MIXED SECONDARY SCHOOL"))
                self.label_2.setText(_translate("MainWindow", "STUDENT ID CARD"))
                self.label_3.setText(_translate("MainWindow", "\"O\" & \"A\" Level"))
                self.label_6.setText(_translate("MainWindow", "NAME:"))
                self.label_7.setText(_translate("MainWindow", "CLASS:"))
                self.label_8.setText(_translate("MainWindow", "YEAR:"))
                self.label_9.setText(_translate("MainWindow", "Issuing Sign:"))
                self.label_10.setText(_translate("MainWindow", "Student\'s Sign:"))
                self.label_11.setText(_translate("MainWindow", "ID No:"))
                self.pushButton.setText(_translate("MainWindow", "SAVE ID"))
                #self.pushButton_2.setText(_translate("MainWindow", "RESET"))
                
        @pyqtSlot()
        def load_pic(self,event):
                image=QFileDialog.getOpenFileName(None,'Select Student Picture','',"Image file(*.*)")
                imagePath=image[0]
                pixmap=QPixmap(imagePath)
                self.label_5.setPixmap(pixmap)
        def change_exp(self):
                date=datetime.date.today()
                year=str(date.strftime('%m-%d-%Y'))
                
                return self.date_issue()+"Expiry Date: "+year
        def current_year(self):
                date=datetime.date.today()
                year=date.strftime("%Y")
                return year
        def date_issue(self):
                date=datetime.date.today()
                d=str(date.strftime('%m-%d-%Y'))
                return 'Issuing Date: ' +d+' | '
        #only uppercase
        def auto_capital(line_edit_object):
                edit=line_edit_object
                text=edit.text()
                edit.text(text.title())
        #print id page
        def compositeEvent(self):
                from PyQt5.QtWidgets import QMessageBox
                with mss.mss() as ID:
                        # The screen part to capture
                        #QtCore.QRect(100, 40, 471, 281)
                        monitor = {"top":60, "left":100, "width": 475, "height": 280}
                        output = self.student_name.text()+"-ID.png".format(**monitor)

                        '''
                        from PIL import Image

                        # Image.open() can also open other image types
                        img = Image.open("some_random_image.jpg")
                        # WIDTH and HEIGHT are integers
                        resized_img = img.resize((WIDTH, HEIGHT))
                        resized_img.save("resized_image.jpg")
                        '''
                        # Grab the data
                        ID_img = ID.grab(monitor)
                        msg = QMessageBox()
                        msg.setWindowTitle("Student's ID ")
                        msg.setIcon(QMessageBox.Information)
                        msg.setText("ID Saved Successfully")
                        msg.exec_()  # this will show our messagebox
                        # Save to the picture file
                        
                        img = Image.open(mss.tools.to_png(ID_img.rgb,ID_img.size, output=output)).size((6,9))
                        #resized_img = img.resize((6,9))                            
                        print(img.save(self.student_name.text()+"-ID.png") )
        def resource_path(self,relative_path):
                """ Get absolute path to resource, works for dev and for PyInstaller """
                try:
                        # PyInstaller creates a temp folder and stores path in _MEIPASS
                        base_path = sys._MEIPASS
                except Exception:
                        base_path = os.path.abspath(".")

                return os.path.join(base_path, relative_path)
        
                ''''
        def handlePrint(self):
                dialog = QtGui.QPrintDialog()
                if dialog.exec_() == QtGui.QDialog.Accepted:
                        self.editor.document().print_(dialog.printer())

        def handlePreview(self):
                dialog = QtGui.QPrintPreviewDialog()
                dialog.paintRequested.connect(self.editor.print_)
                dialog.exec_()

        def handleTextChanged(self):
                enable = not self.editor.document().isEmpty()
                self.buttonPrint.setEnabled(enable)
                self.buttonPreview.setEnabled(enable)
         '''     
        def handlePreview(self):
                # dialog = QtPrintSupport.QPrintPreviewDialog() # PyQt5
                dialog =QPrintPreviewDialog()
                dialog.update()
                dialog.paintRequested.connect(self.handlePaintRequest)
                dialog.exec_()

        def handlePaintRequest(self, printer):
                self.listWidget.render(QtGui.QPainter(printer)) 
                self.i_exp_date.render(QtGui.QPainter(printer)) 
                self.c_class.render(QtGui.QPainter(printer))
                self.c_year.render(QtGui.QPainter(printer)) 
        #others
       

if __name__ == "__main__":
    import sys
    app =QApplication (sys.argv)
    
    mainWindow =QMainWindow() #win=QWidget()
    ui = Ui_MainWindow()
    app.setWindowIcon(QIcon(ui.resource_path('zms_badge.png')))
    ui.setupUi(mainWindow)
    mainWindow.showMaximized()
    sys.exit(app.exec_())
    
    
